### ISSUE TITLE
Mermaid graph click option not working with links.

### ISSUE THREAD

**Issue by spd-spd** [RobertWeinmeister/dokuwiki-mermaid#8]
### Versions:
DokuWiki: JackJackrum
mermaidplugin: 2023-07-18
mermaid version: locally hosted 10.2.4(CJS)

### Problem:
This mermaid graph shows, however node C does not properly generate the same link as node B.
```
<mermaid> 
graph TD;
  A-->B[["[[wiki:start]]"]];
  A[[A]]-->C;
  C[[undGehtDas]];
  B-->D;
  C-->D;
  click C "wiki:start" _self;
</mermaid>

```
Alternatively, this link if placed in code above becomes mangled:
`  click C "https://www.dokuwiki.org/dokuwiki" _self;
`

**Comment by RobertWeinmeister** [comment]
The problem is both Mermaid and DokuWiki want to handle links. This clash is almost unavoidable. The solution to this would be to write your own link renderer (or even parser) to use when processing Mermaid code and use this instead of the standard implementation used by DokuWiki itself.

[["[[wiki:start|Start]]"]] works perfectly fine now so I do not see a good use case to support binding click events that would justify the effort.

I am open to suggestions or to revisit this if for some reason this is an important part missed (or if someone wants the code for this).

**Comment by spd-spd** [comment]
There are also only so many punctuation characters to go around.  Thank you for the clarification and the documentation update.
